export class AcParent {
public  parent_ref: string;
public  student_ref: string;
public  parent_flag: string;
public  relationship_status: string;
public  because: string;
public  father_pid: string;
public  father_status: string;
public  father_died_year: string;
public  father_name: string;
public  father_birth_date: Date;
public  father_address: string;
public  father_province: string;
public  father_district: string;
public  father_sub_district: string;
public  father_postcode: string;
public  father_phone: string;
public  father_email: string;
public  father_occupation: string;
public  father_position: string;
public  father_work_address: string;
public  father_work_phone: string;
public  father_work_fax: string;
public  father_land_flag: string;
public  father_land_all: number;
public  father_land_own: number;
public  father_land_rent: number;
public  father_income_monthly: number;
public  mother_pid: string;
public  mother_status: string;
public  mother_died_year: string;
public  mother_name: string;
public  mother_birth_date: Date;
public  mother_address: string;
public  mother_province: string;
public  mother_district: string;
public  mother_sub_district: string;
public  mother_postcode: string;
public  mother_phone: string;
public  mother_email: string;
public  mother_occupation: string;
public  mother_position: string;
public  mother_work_address: string;
public  mother_work_phone: string;
public  mother_work_fax: string;
public  mother_land_flag: string;
public  mother_land_all: number;
public  mother_land_own: number;
public  mother_land_rent: number;
public  mother_income_monthly: number;
public  patrol_relationship: string;
public  patrol_pid: string;
public  patrol_status: string;
public  patrol_died_year: string;
public  patrol_name: string;
public  patrol_birth_date: Date;
public  patrol_address: string;
public  patrol_province: string;
public  patrol_district: string;
public  patrol_sub_district: string;
public  patrol_postcode: string;
public  patrol_phone: string;
public  patrol_email: string;
public  patrol_occupation: string;
public  patrol_position: string;
public  patrol_work_address: string;
public  patrol_work_phone: string;
public  patrol_work_fax: string;
public  patrol_land_flag: string;
public  patrol_land_all: number;
public  patrol_land_own: number;
public  patrol_land_rent: number;
public  patrol_income_monthly: number;
public  create_user: string;
public  create_datetime: Date;
public  update_user: string;
public  update_datetime:Date;

constructor(){
this.parent_ref=null;
this.student_ref=null;
this.parent_flag=null;
this.relationship_status=null;
this.because=null;
this.father_pid=null;
this.father_status=null;
this.father_died_year=null;
this.father_name=null;
this.father_birth_date=null;
this.father_address=null;
this.father_province=null;
this.father_district=null;
this.father_sub_district=null;
this.father_postcode=null;
this.father_phone=null;
this.father_email=null;
this.father_occupation=null;
this.father_position=null;
this.father_work_address=null;
this.father_work_phone=null;
this.father_work_fax=null;
this.father_land_flag=null;
this.father_land_all=null;
this.father_land_own=null;
this.father_land_rent=null;
this.father_income_monthly=null;
this.mother_pid=null;
this.mother_status=null;
this.mother_died_year=null;
this.mother_name=null;
this.mother_birth_date=null;
this.mother_address=null;
this.mother_province=null;
this.mother_district=null;
this.mother_sub_district=null;
this.mother_postcode=null;
this.mother_phone=null;
this.mother_email=null;
this.mother_occupation=null;
this.mother_position=null;
this.mother_work_address=null;
this.mother_work_phone=null;
this.mother_work_fax=null;
this.mother_land_flag=null;
this.mother_land_all=null;
this.mother_land_own=null;
this.mother_land_rent=null;
this.mother_income_monthly=null;
this.patrol_relationship=null;
this.patrol_pid=null;
this.patrol_status=null;
this.patrol_died_year=null;
this.patrol_name=null;
this.patrol_birth_date=null;
this.patrol_address=null;
this.patrol_province=null;
this.patrol_district=null;
this.patrol_sub_district=null;
this.patrol_postcode=null;
this.patrol_phone=null;
this.patrol_email=null;
this.patrol_occupation=null;
this.patrol_position=null;
this.patrol_work_address=null;
this.patrol_work_phone=null;
this.patrol_work_fax=null;
this.patrol_land_flag=null;
this.patrol_land_all=null;
this.patrol_land_own=null;
this.patrol_land_rent=null;
this.patrol_income_monthly=null;
this.create_user=null;
this.create_datetime=null;
this.update_user=null;
this.update_datetime=null;
}
}
